### ISSUE TITLE
Turn benjaminsampica to a special repository

### ISSUE THREAD

**Issue by emmysteven** [benjaminsampica/benjaminsampica#339]
Hi, 

Please don't be offended, I don't know how this might appear to you.
In my honest opinion I do think you should make this repository a special repository by making the readme more about you as a develop like this one 👉🏻 [emmysteven](https://github.com/emmysteven/emmysteven)

I'm in no place to tell you what to do, I'm just suggesting 🙏

Thanks!

**Comment by benjaminsampica** [comment]
I appreciate the feedback. I've got other avenues to showcase who I am as a developer such as a static website I maintain at [bensampica.com](www.bensampica.com). 

Dungeons & Dragons is very special to me, especially during this time where we are all making efforts to keep each other safe. To that end, I found the "game" of this repository to be very unique among the other developer readmes I had run across. 

Thanks for the suggestion! 👍🏻
